# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew and is not meant to be edited directly.
# For details, see: https://docs.brew.sh/Formula-Cookbook

class Schoolcode < Formula
  desc "Automated developer tool deployment for macOS Guest accounts"
  homepage "https://github.com/luka-loehr/schoolcode"
  url "https://github.com/luka-loehr/schoolcode/releases/download/v3.0.0/schoolcode-3.0.0.tar.gz"
  sha256 "e62a370376b85b1e4317d8c861152070e7c8a1fdaecddfb2c4e3463fad8c13c6" # Will be calculated after creating release
  license "Apache-2.0"
  head "https://github.com/luka-loehr/schoolcode.git", branch: "main"

  depends_on "bash"

  def install
    # Install main script as executable
    bin.install "schoolcode.sh" => "schoolcode"
    
    # Install all scripts to libexec/scripts
    libexec.install Dir["scripts"]
    
    # Make all scripts executable
    Dir["#{libexec}/**/*.sh"].each { |f| chmod 0755, f }
  end

  def post_install
    # Run SchoolCode installation script
    # This will perform full installation: compatibility check, system repair, tool installation, guest setup
    system "sudo", "#{bin}/schoolcode"
  end

  def uninstall
    # Run SchoolCode uninstall script before removing package
    if File.exist?("#{bin}/schoolcode")
      system "sudo", "#{bin}/schoolcode", "--uninstall"
    end
  end

  test do
    # Test that the command exists and shows help
    system "#{bin}/schoolcode", "--help"
  end
end

